<script lang="ts">
  // ===============
  // onMount actions
  // ===============
  
  import { show } from '$lib/helpers';
  import { onMount } from 'svelte';
  onMount(async () => {
    await load_summaries()
  })

  //
  // load summaries
  //

  let summaries: summary[] = []
  import { supabase } from "$lib/supabaseClient";
  async function load_summaries() {
    try {
      const { data, error } = await supabase
        .from("summaries")
        .select();

      if (error) throw error
      summaries = data ?? []
    } catch (error) { 
      show(error)
      summaries = [] 
    } finally {
      // show(summaries)
    }
  }

  //
  // add project
  //

  // Renamed variables to snake_case for consistency
  let show_add_modal = false;
  let project_form: project = {
    code: '',
    title: '',
    tax: 10,
    authorized_rep: '',
    approver: '',
    admin_officer: ''
  };

  async function add_project(new_project: project) {    
    try {
      const { data, error } = await supabase
        .from("projects")
        .insert(new_project)

      if (error) throw error
      alert("project added succesfully")
    } catch (error) {
      alert("error inserting to database")
    }
  }

  function open_add_modal() {
    show_add_modal = true;
  }
  function close_add_modal() {
    show_add_modal = false;
  }
  async function handle_create_project() {
    await add_project(project_form);
    close_add_modal();
    await load_summaries();
    // Reset form
    project_form = {
      code: '',
      title: '',
      tax: 0,
      authorized_rep: '',
      approver: '',
      admin_officer: ''
    };
  }

  // Edit Project Modal
  let show_edit_modal = false;
  let edit_form: project = {
    code: '',
    id: undefined,
    title: '',
    tax: 0,
    authorized_rep: '',
    approver: '',
    admin_officer: ''
  };

  function open_edit_modal(s: summary) {
    edit_form.code = s.code
    edit_form.id = s.project_id
    edit_form.title = s.title
    edit_form.authorized_rep = s.authorized_rep
    edit_form.approver = s.approver
    edit_form.admin_officer = s.admin_officer
    edit_form.tax = s.tax

    show_edit_modal = true;
  }
  
  function close_edit_modal() {
    show_edit_modal = false;
  }

  async function handle_edit_project() {
    try {
      // alert(edit_form.project_id)
      const { data, error } = await supabase
        .from("projects")
        .update({
          code: edit_form.code,
          title: edit_form.title,
          tax: edit_form.tax,
          authorized_rep: edit_form.authorized_rep,
          approver: edit_form.approver,
          admin_officer: edit_form.admin_officer
        })
        .eq('id', edit_form.id);
      if (error) throw error;
      alert("project updated successfully");
      close_edit_modal();
      await load_summaries();
    } catch (error) {
      alert("error updating project");
    }
  }

  // id is auto generated by the database, it should not be a parameter when inserting
  // it should be used, however, to uniquely identify a project
  // interface project {
	// 	code: string,
	// 	id?: number,
	// 	title: string,
	// 	tax: number,	
	// 	authorized_rep: string,
	// 	approver: string,
	// 	admin_officer: string,
	// }

</script>



<div class="page-header">
  <h1 class="page-title">Projects</h1>
  <span class="text-gray-600/70">|</span>
  <button class="add-project-btn" on:click={open_add_modal}>
    + Add Project
  </button>
</div>

{#if show_add_modal}
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div class="modal-backdrop" on:click={close_add_modal}></div>
  <div class="modal">
    <h2 class="modal-title">Add New Project</h2>
    <form on:submit|preventDefault={handle_create_project}>
      <label>Code
        <input type="text" bind:value={project_form.code} required />
      </label>
      <label>Title
        <input type="text" bind:value={project_form.title} required />
      </label>
      <label>Tax (%)
        <input type="number" bind:value={project_form.tax} min="0" step="0.01" required />
      </label>
      <label>Authorized Rep
        <input type="text" bind:value={project_form.authorized_rep} required />
      </label>
      <label>Approver
        <input type="text" bind:value={project_form.approver} required />
      </label>
      <label>Admin Officer
        <input type="text" bind:value={project_form.admin_officer} required />
      </label>
      <div class="modal-actions">
        <button type="button" class="modal-cancel" on:click={close_add_modal}>Cancel</button>
        <button type="submit" class="modal-submit">Create</button>
      </div>
    </form>
  </div>
{/if}

{#if show_edit_modal}
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div class="modal-backdrop" on:click={close_edit_modal}></div>
  <div class="modal">
    <h2 class="modal-title">Edit Project</h2>
    <form on:submit|preventDefault={handle_edit_project}>
      <label>Code
        <input type="text" bind:value={edit_form.code} required />
      </label>
      <label>Title
        <input type="text" bind:value={edit_form.title} required />
      </label>
      <label>Tax (%)
        <input type="number" bind:value={edit_form.tax} min="0" step="0.01" required />
      </label>
      <label>Authorized Rep
        <input type="text" bind:value={edit_form.authorized_rep} required />
      </label>
      <label>Approver
        <input type="text" bind:value={edit_form.approver} required />
      </label>
      <label>Admin Officer
        <input type="text" bind:value={edit_form.admin_officer} required />
      </label>
      <div class="modal-actions">
        <button type="button" class="modal-cancel" on:click={close_edit_modal}>Cancel</button>
        <button type="submit" class="modal-submit">Save</button>
      </div>
    </form>
  </div>
{/if}

<table class="summary-table border-2 border-green-800">
  <thead>
    <tr>
      <th>Code</th>
      <th>Title</th>
      <th>Authorized Representative</th>
      <th>Approver</th>
      <th>Admin Officer</th>
      <th>Total Vouchers</th>
      <th>Gross Total</th>
      <th>Net Total</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    {#each summaries as s}
      <tr>
        <td>{s.code}</td>
        <td>{s.title}</td>
        <td>{s.authorized_rep}</td>
        <td>{s.approver}</td>
        <td>{s.admin_officer}</td>
        <td>{s.total_vouchers}</td>
        <td>{s.gross_total}</td>
        <td>{s.net_total}</td>
        <td class="flex gap-3">
          <!-- svelte-ignore a11y_click_events_have_key_events -->
          <!-- svelte-ignore a11y_no_static_element_interactions -->
          <span class="text-blue-500 hover:underline cursor-pointer" on:click={() => open_edit_modal(s)}>Edit</span>
          <span class="text-red-500 hover:underline cursor-pointer">Delete</span>
        </td>
      </tr>
    {/each}
  </tbody>
</table>

<style>
.page-header {
  display: flex;
  align-items: center;
  justify-content: start;
  margin-bottom: 1.5rem;
  margin-top: 1rem;
  gap: 1rem;
}

.page-title {
  font-size: 2rem;
  font-weight: 700;
  color: oklch(44.8% 0.119 151.328); /* deep green */
  letter-spacing: -0.5px;
  margin: 0;
}

.add-project-btn {
  background: oklch(44.8% 0.119 151.328);
  color: #fff;
  font-size: 1rem;
  font-weight: 600;
  padding: 0.7rem 1.5rem;
  border: none;
  border-radius: 0.5rem;
  cursor: pointer;
  transition: background 0.15s;
  box-shadow: 0 2px 8px 0 rgba(44, 62, 80, 0.04);
}
.add-project-btn:hover,
.add-project-btn:focus {
  background: oklch(34.389% 0.09873 148.331);
  outline: none;
}

.summary-table {
  width: 100%;
  border-collapse: collapse;
  margin-top: 0;
}
.summary-table th {
  background: oklch(44.8% 0.119 151.328); /* dark green */
  color: #fff;
  padding: 0.75rem 1rem;
  text-align: left;
}
.summary-table td {
  background: #fff;
  color: #111;
  padding: 0.75rem 1rem;
  border-bottom: 1px solid #e5e5e5;
}
.summary-table tr:last-child td {
  border-bottom: none;
}

.modal-backdrop {
  position: fixed;
  top: 0; left: 0; right: 0; bottom: 0;
  background: rgba(0,0,0,0.25);
  z-index: 40;
}
.modal {
  position: fixed;
  top: 50%; left: 50%;
  transform: translate(-50%, -50%);
  background: #fff;
  padding: 2rem 2.5rem;
  border-radius: 1rem;
  box-shadow: 0 8px 32px 0 rgba(44, 62, 80, 0.18);
  z-index: 50;
  min-width: 320px;
  max-width: 95vw;
}
.modal-title {
  font-size: 1.3rem;
  font-weight: 700;
  margin-bottom: 1.2rem;
  color: oklch(44.8% 0.119 151.328);
}
.modal label {
  display: block;
  margin-bottom: 0.7rem;
  font-weight: 500;
  color: #222;
}
.modal input[type="text"], .modal input[type="number"] {
  width: 100%;
  padding: 0.5rem 0.7rem;
  margin-top: 0.2rem;
  margin-bottom: 0.2rem;
  border: 1px solid #cbd5e1;
  border-radius: 0.4rem;
  font-size: 1rem;
  background: #f9fafb;
  transition: border 0.15s;
}
.modal input:focus {
  border: 1.5px solid oklch(44.8% 0.119 151.328);
  outline: none;
}
.modal-actions {
  display: flex;
  justify-content: flex-end;
  gap: 0.7rem;
  margin-top: 1.2rem;
}
.modal-cancel {
  background: #e5e7eb;
  color: #222;
  border: none;
  padding: 0.5rem 1.2rem;
  border-radius: 0.4rem;
  font-weight: 500;
  cursor: pointer;
  transition: background 0.15s;
}
.modal-cancel:hover {
  background: #d1d5db;
}
.modal-submit {
  background: oklch(44.8% 0.119 151.328);
  color: #fff;
  border: none;
  padding: 0.5rem 1.2rem;
  border-radius: 0.4rem;
  font-weight: 600;
  cursor: pointer;
  transition: background 0.15s;
}
.modal-submit:hover {
  background: oklch(34.389% 0.09873 148.331);
}
</style>